<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ShadowForge.CLI</RootNamespace>
    <AssemblyName>sforge</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShadowForge.Core\ShadowForge.Core.csproj" />
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.15" />
  </ItemGroup>
</Project>
