using System.Text;

namespace ShadowForge.Generators;

internal static class MarshalSourceWriter
{
    public static string Write(StructInfo info, List<FieldInfo> fields)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(info.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").AppendLine(info.Namespace);
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";
        string body = indent + "        ";

        sb.Append(indent).Append("partial struct ").AppendLine(info.TypeName);
        sb.Append(indent).AppendLine("{");

        if (info.DeclaredSize > 0)
        {
            sb.Append(indent).AppendLine("    public const int Size = " + info.DeclaredSize + ";");
            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("    public static " + info.TypeName + " Read(ReadOnlySpan<byte> data)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(body).AppendLine("var result = new " + info.TypeName + "();");
        foreach (var f in fields)
            sb.Append(body).AppendLine("result." + f.Name + " = " + ReadExpression(f) + ";");
        sb.Append(body).AppendLine("return result;");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        sb.Append(indent).AppendLine("    public static void Write(Span<byte> data, in " + info.TypeName + " value)");
        sb.Append(indent).AppendLine("    {");
        foreach (var f in fields)
        {
            foreach (string statement in WriteStatements(f))
                sb.Append(body).AppendLine(statement + ";");
        }
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("}");
        if (hasNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ReadExpression(FieldInfo f)
    {
        int o = f.Offset;
        return f.Kind switch
        {
            FieldKind.Primitive => ReadInteger(f.Keyword!, o),
            FieldKind.Float => ReadSingle(o),
            FieldKind.Double => "BitConverter.UInt64BitsToDouble(BinaryPrimitives.ReadUInt64BigEndian(data.Slice(" + o + ")))",
            FieldKind.Vector3 => "new System.Numerics.Vector3("
                + ReadSingle(o) + ", " + ReadSingle(o + 4) + ", " + ReadSingle(o + 8) + ")",
            FieldKind.EncodedString => "data.Slice(" + o + ", " + f.EncodedStringLength + ").ToArray()",
            FieldKind.Enum => "(" + f.TypeName + ")" + ReadInteger(f.Keyword!, o),
            FieldKind.Nested => f.NestedStructFullName + ".Read(data.Slice(" + o + ", " + f.Size + "))",
            _ => "default",
        };
    }

    private static IEnumerable<string> WriteStatements(FieldInfo f)
    {
        int o = f.Offset;
        string val = "value." + f.Name;
        switch (f.Kind)
        {
            case FieldKind.Primitive:
                yield return WriteInteger(f.Keyword!, o, val);
                break;
            case FieldKind.Float:
                yield return WriteSingle(o, val);
                break;
            case FieldKind.Double:
                yield return "BinaryPrimitives.WriteUInt64BigEndian(data.Slice(" + o + "), BitConverter.DoubleToUInt64Bits(" + val + "))";
                break;
            case FieldKind.Vector3:
                yield return WriteSingle(o, val + ".X");
                yield return WriteSingle(o + 4, val + ".Y");
                yield return WriteSingle(o + 8, val + ".Z");
                break;
            case FieldKind.EncodedString:
                yield return "if (" + val + " != null) " + val + ".AsSpan().CopyTo(data.Slice(" + o + ", " + f.EncodedStringLength + "))";
                break;
            case FieldKind.Enum:
                yield return WriteInteger(f.Keyword!, o, "(" + f.Keyword + ")" + val);
                break;
            case FieldKind.Nested:
                yield return f.NestedStructFullName + ".Write(data.Slice(" + o + ", " + f.Size + "), in " + val + ")";
                break;
        }
    }

    private static string ReadSingle(int o)
        => "BitConverter.UInt32BitsToSingle(BinaryPrimitives.ReadUInt32BigEndian(data.Slice(" + o + ")))";

    private static string WriteSingle(int o, string val)
        => "BinaryPrimitives.WriteUInt32BigEndian(data.Slice(" + o + "), BitConverter.SingleToUInt32Bits(" + val + "))";

    private static string ReadInteger(string keyword, int o)
        => keyword == "byte"
            ? "data[" + o + "]"
            : "BinaryPrimitives.Read" + BinaryPrimitivesName(keyword) + "BigEndian(data.Slice(" + o + "))";

    private static string WriteInteger(string keyword, int o, string val)
        => keyword == "byte"
            ? "data[" + o + "] = " + val
            : "BinaryPrimitives.Write" + BinaryPrimitivesName(keyword) + "BigEndian(data.Slice(" + o + "), " + val + ")";

    private static string BinaryPrimitivesName(string keyword) => keyword switch
    {
        "ushort" => "UInt16",
        "short" => "Int16",
        "uint" => "UInt32",
        "int" => "Int32",
        "ulong" => "UInt64",
        _ => "Int64",
    };
}
