<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ShadowForge</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ShadowForge.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.*" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.*" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Tomlyn" Version="0.19.0" />
    <ProjectReference Include="..\ShadowForge.Core.Generators\ShadowForge.Core.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
